### ISSUE TITLE
Extract text webpack plugin is throwing errors

### ISSUE THREAD

**Issue by cjackson234** [easy-webpack/config-css#30]
I am getting the following error

`@easy-webpack\config-sass\node_modules\extract-text-webpack-plugin\schema\validator.js:11
                throw new Error(ajv.errorsText());`

It seems like extract-text-webpack-plugin has updated.

**Comment by cjackson234** [comment]
ajv doesn't even exist in the package as of December when I started this app.

**Comment by niieani** [comment]
This was already fixed a few days ago. The breaking change was introduced few days ago to `extract-text-webpack-plugin`. Just update to the latest version of `config-css`.

Please update to the latest version (config-css v4.0.1).

**Comment by cjackson234** [comment]
That didn't fix it for me. Now I get
`Cannot find module 'ajv'`

**Comment by niieani** [comment]
@cjackson234 can you try to remove node_modules and install again? if that doesn't work, can you paste your package.json file?

**Comment by cjackson234** [comment]
I have already done this. Still the same issue.

Here are my dependecies from the package.json

> "dependencies": {
>     "aurelia-auth": "^3.0.4",
>     "aurelia-bootstrapper-webpack": "^1.0.0",
>     "aurelia-configuration": "1.0.14",
>     "aurelia-cookie": "^1.0.10",
>     "aurelia-dialog": "^1.0.0-beta.3.0.1",
>     "aurelia-event-aggregator": "^1.0.0",
>     "aurelia-fetch-client": "^1.0.0",
>     "aurelia-framework": "^1.0.0",
>     "aurelia-history-browser": "^1.0.0",
>     "aurelia-loader-webpack": "^1.0.0",
>     "aurelia-logging-console": "^1.0.0",
>     "aurelia-mdl-plugin": "^0.1.15",
>     "aurelia-notification": "^1.0.0",
>     "aurelia-pal-browser": "^1.0.0",
>     "aurelia-polyfills": "^1.0.0",
>     "aurelia-route-recognizer": "^1.0.0",
>     "aurelia-router": "^1.0.2",
>     "aurelia-templating-binding": "^1.0.0",
>     "aurelia-templating-resources": "^1.0.0",
>     "aurelia-templating-router": "^1.0.0",
>     "bluebird": "^3.4.1",
>     "bootstrap": "^3.3.7",
>     "eonasdan-bootstrap-datetimepicker": "^4.17.43",
>     "extract-text-webpack-plugin": "^1.0.1",
>     "font-awesome": "^4.6.3",
>     "isomorphic-fetch": "^2.2.1",
>     "jquery": "^3.1.0",
>     "lodash": "^4.16.4",
>     "material-design-icons": "^3.0.1",
>     "material-design-lite": "^1.2.1",
>     "mdl-selectfield": "^1.0.2",
>     "moment": "^2.17.1",
>     "toastr": "^2.1.2",
>     "whatwg-fetch": "^2.0.1"
>   },
>   "devDependencies": {
>     "@easy-webpack/config-aurelia": "^2.0.1",
>     "@easy-webpack/config-babel": "^2.0.2",
>     "@easy-webpack/config-common-chunks-simple": "^2.0.1",
>     "@easy-webpack/config-copy-files": "^1.0.0",
>     "@easy-webpack/config-css": "4.0.1",
>     "@easy-webpack/config-env-development": "^2.1.1",
>     "@easy-webpack/config-env-production": "^2.1.0",
>     "@easy-webpack/config-external-source-maps": "^2.0.1",
>     "@easy-webpack/config-fonts-and-images": "^1.2.1",
>     "@easy-webpack/config-generate-index-html": "^2.0.1",
>     "@easy-webpack/config-global-bluebird": "^1.2.0",
>     "@easy-webpack/config-global-jquery": "^1.2.0",
>     "@easy-webpack/config-global-regenerator": "^1.2.0",
>     "@easy-webpack/config-html": "^2.0.2",
>     "@easy-webpack/config-json": "^2.0.2",
>     "@easy-webpack/config-sass": "1.2.0",
>     "@easy-webpack/config-source-map-support": "^1.0.0",
>     "@easy-webpack/config-test-coverage-istanbul": "^2.0.2",
>     "@easy-webpack/config-typescript": "^2.1.2",
>     "@easy-webpack/config-uglify": "^2.1.0",
>     "@easy-webpack/core": "^1.3.2",
>     "@types/bluebird": "^2.0.29",
>     "@types/jasmine": "^2.2.30",
>     "@types/whatwg-fetch": "0.0.27",
>     "aurelia-tools": "^0.2.4",
>     "autoprefixer": "^6.5.3",
>     "babel-plugin-transform-decorators-legacy": "^1.3.4",
>     "babel-preset-es2015": "^6.9.0",
>     "babel-preset-es2015-loose": "^7.0.0",
>     "babel-preset-es2015-loose-native-modules": "^1.0.0",
>     "babel-preset-stage-1": "^6.5.0",
>     "babel-register": "^6.11.6",
>     "concurrently": "^2.2.0",
>     "cross-env": "^2.0.0",
>     "http-server": "^0.9.0",
>     "jasmine-core": "^2.4.1",
>     "karma": "^1.1.2",
>     "karma-chrome-launcher": "^1.0.1",
>     "karma-coverage": "^1.1.1",
>     "karma-jasmine": "^1.0.2",
>     "karma-mocha-reporter": "^2.0.4",
>     "karma-remap-istanbul": "^0.1.1",
>     "karma-sourcemap-loader": "^0.3.7",
>     "karma-webpack": "^1.7.0",
>     "postcss-loader": "^1.1.1",
>     "rimraf": "^2.5.4",
>     "ts-node": "^1.2.1",
>     "tslint": "^3.15.1",
>     "tslint-loader": "^2.1.5",
>     "typescript": "2.0.10",
>     "wait-on": "^1.5.2",
>     "webpack": "2.1.0-beta.22",
>     "webpack-dev-server": "2.1.0-beta.9"
>   },

**Comment by cjackson234** [comment]
@niieani installing the ajv node package brings me back to the first error.

**Comment by niieani** [comment]
You have `extract-text-webpack-plugin` version 1.0.1. Please remove that package from dependencies. @easy-webpack installs version 2-beta.

**Comment by cjackson234** [comment]
@niieani, so that actually installs `2.0.0-rc.2`. However, that still didn't fix it for me.

**Comment by niieani** [comment]
Please reinstall node_modules after uninstalling extract-text-webpack-plugin from dependencies. `ajv` is a dependency of the 2.0.0-rc.2 version, as you can see [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/cc8e1ca7474e60086e7e2b90952de5a244e1bc35/package.json#L13), so npm/yarn has to install it.

**Comment by cjackson234** [comment]
I completely deleted all node modules. Installed yarn. Used yarn to reinstall node packages. Retried build. Still getting the same error.

**Comment by cjackson234** [comment]
Does my webpack version matter?`
 "webpack": "2.1.0-beta.22",
    "webpack-dev-server": "2.1.0-beta.9"`

**Comment by cjackson234** [comment]
Everything works now. Here is my finalized package.json file 

> "dependencies": {
    "aurelia-auth": "3.0.5",
    "aurelia-bootstrapper-webpack": "^1.1.0",
    "aurelia-configuration": "1.0.14",
    "aurelia-cookie": "^1.0.10",
    "aurelia-dialog": "^1.0.0-beta.3.0.1",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-fetch-client": "^1.0.1",
    "aurelia-framework": "^1.0.7",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-loader-webpack": "^1.0.3",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-mdl-plugin": "^0.1.15",
    "aurelia-notification": "^1.0.0",
    "aurelia-pal-browser": "^1.0.0",
    "aurelia-polyfills": "^1.1.1",
    "aurelia-route-recognizer": "^1.1.0",
    "aurelia-router": "^1.0.7",
    "aurelia-templating-binding": "^1.1.0",
    "aurelia-templating-resources": "^1.2.0",
    "aurelia-templating-router": "^1.0.0",
    "aurelia-ui-virtualization": "^1.0.0-beta.3.0.2",
    "bluebird": "^3.4.1",
    "bootstrap": "^3.3.7",
    "eonasdan-bootstrap-datetimepicker": "^4.17.43",
    "font-awesome": "^4.6.3",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.1.0",
    "lodash": "^4.16.4",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.2.1",
    "mdl-selectfield": "^1.0.2",
    "moment": "^2.17.1",
    "toastr": "^2.1.2",
    "whatwg-fetch": "^2.0.1"
  },
  "devDependencies": {
    "@easy-webpack/config-aurelia": "^2.2.2",
    "@easy-webpack/config-common-chunks-simple": "^2.0.3",
    "@easy-webpack/config-copy-files": "^1.1.2",
    "@easy-webpack/config-css": "^4.0.0",
    "@easy-webpack/config-sass": "^4.0.0",
    "@easy-webpack/config-env-development": "^2.1.5",
    "@easy-webpack/config-env-production": "^3.0.0",
    "@easy-webpack/config-external-source-maps": "^3.1.0",
    "@easy-webpack/config-fonts-and-images": "^2.1.0",
    "@easy-webpack/config-generate-index-html": "^2.1.1",
    "@easy-webpack/config-global-bluebird": "^2.1.0",
    "@easy-webpack/config-global-jquery": "^2.1.0",
    "@easy-webpack/config-html": "^3.1.0",
    "@easy-webpack/config-json": "^3.1.0",
    "@easy-webpack/config-source-map-support": "^1.0.2",
    "@easy-webpack/config-test-coverage-istanbul": "^3.2.0",
    "@easy-webpack/config-typescript": "^5.0.0",
    "@easy-webpack/config-uglify": "^2.2.3",
    "@easy-webpack/core": "^2.0.0",
    "@types/bluebird": "^3.0.35",
    "@types/jasmine": "^2.5.38",
    "@types/node": "^6.0.48",
    "@types/webpack": "^2.0.0",
    "@types/whatwg-fetch": "^0.0.32",
    "aurelia-tools": "^0.2.4",
    "autoprefixer": "^6.5.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-es2015-loose-native-modules": "^1.0.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-register": "^6.11.6",
    "concurrently": "^2.2.0",
    "cross-env": "^2.0.0",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.4.1",
    "karma": "^1.1.2",
    "karma-chrome-launcher": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.4",
    "karma-remap-istanbul": "^0.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "postcss-loader": "^1.1.1",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "tslint-loader": "^2.1.5",
    "ts-node": "^1.7.2",
    "typescript": "^2.1",
    "wait-on": "^2.0.1",
    "wallaby-webpack": "0.0.26",
    "webpack": "2.1.0-beta.27",
    "webpack-dev-server": "2.1.0-beta.12"
  },

**Comment by cjackson234** [comment]
also, assure that you have deleted your `.awcache` folder.

**Comment by niieani** [comment]
Thanks for pasting the package.json, what was the problem?
